query myConcepts(
  $where: KBConceptWhereInput
  $orderBy: KBConceptOrderByInput
  $skip: Int
  $take: Int
  $detailedInfo: Boolean = false
) {
  response: myConcepts(
    where: $where
    orderBy: $orderBy
    skip: $skip
    take: $take
  ) {
    ...KBConcept_
  }
}

query myConcept($id: String!, $detailedInfo: Boolean = true) {
  response: myConcept(id: $id) {
    ...KBConcept_
  }
}

query concepts(
  $where: KBConceptWhereInput
  $orderBy: KBConceptOrderByInput
  $skip: Int
  $take: Int
  $detailedInfo: Boolean = true
) {
  response: concepts(
    where: $where
    orderBy: $orderBy
    skip: $skip
    take: $take
  ) {
    ...KBConcept_
  }
}

mutation createConcept(
  $data: KBConceptCreateInput!
  $detailedInfo: Boolean = true
) {
  response: createConcept(data: $data) {
    ...KBConcept_
  }
}

mutation updateConcept(
  $id: String!
  $data: KBConceptUpdateInput!
  $detailedInfo: Boolean = true
) {
  response: updateConcept(id: $id, data: $data) {
    ...KBConcept_
  }
}

mutation deleteConcept($id: String!) {
  response: deleteConcept(id: $id) {
    id
  }
}

fragment KBConcept_ on KBConcept {
  ...KBConceptNoNesting
}

fragment KBConceptNoNesting on KBConcept {
  id
  # createdAt
  updatedAt
  type
  name
  description
  createdById
  content @include(if: $detailedInfo)
}
